import type { Metadata } from "next";
import "./globals.css";
import { HeroUIProvider } from "@heroui/system";
import { ThemeProvider as NextThemesProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <HeroUIProvider>
          <NextThemesProvider
            attribute="class"
            defaultTheme="dark"
            themes={[
              "dark",
              "light",
              "ceres",
              "umbriel",
              "neptune",
              "callisto",
            ]}
          >
            <main className="min-h-screen">{children}</main>
          </NextThemesProvider>
        </HeroUIProvider>
      </body>
    </html>
  );
}
