import type { Metadata } from "next";
import "./globals.css";
import { HeroUIProvider } from "@heroui/system";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SessionProvider session={session}>
          <HeroUIProvider>
            <NextThemesProvider
              attribute="class"
              defaultTheme="dark"
              themes={[
                "dark",
                "light",
                "ceres",
                "umbriel",
                "neptune",
                "callisto",
              ]}
            >
              <main className="min-h-screen">{children}</main>
            </NextThemesProvider>
          </HeroUIProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
